### ISSUE TITLE
batch.clear() feature

### ISSUE THREAD

**Issue by hlobil** [hypercore-protocol/hyperbee#10]
hyperbee has ]batch.flush() which is similar to batch.write() on levelup

batch.clear()  example https://github.com/Level/levelup#dbbatch-chained-form

it does not have concept of batch.clear() is there a reason for this?

there is batch.blocks.clear() but if I use it I get an error on batch.flush()

**Comment by mafintosh** [comment]
We don't support clear() (I actually didn't know level had that!). We can tho in the future so thanks for opening the issue.
If something wants to try tackling this it would require resetting all the state on the batch object and adding tests.
