### ISSUE TITLE
Change notification?

### ISSUE THREAD

**Issue by kamilchm** [hypercore-protocol/hyperbee#23]
Is there a way to get notifications about changes, like [db.watch in hyperdb](https://github.com/mafintosh/hyperdb#watcher--dbwatchfolderorkey-onchange)?

**Comment by mafintosh** [comment]
atm you'll have to use the diff stream for that. we should def add a helper for that.

**Comment by davetapley** [comment]
[hypertrie](https://github.com/hypercore-protocol/hypertrie) also offers this as [`db.watch(..)`](https://github.com/hypercore-protocol/hypertrie#const-watcher--dbwatchprefix-onchange).

It uses [`feed.on('append',...)`](https://github.com/hypercore-protocol/hypertrie/blob/4601facc32e5163c94e6d95d475426a35218f2d8/index.js#L103-L105), then [checks `seq`](https://github.com/hypercore-protocol/hypertrie/blob/37dc7925d6f839b966528f62bdaaa5d2e99acccb/lib/watch.js#L35-L59) to see if it needs to emit an event.
@mafintosh I'm not familiar with diff stream, is there a reason to prefer that approach to this one? 🤔

**Comment by mafintosh** [comment]
Diff is very efficient on large updates. Having a watch method that tells if you a prefix has changed makes sense as well

**Comment by LuKks** [comment]
`db.watch([range])` added: https://github.com/holepunchto/hyperbee/pull/81
