### ISSUE TITLE
Is it possible to have an on('update') event on subs?

### ISSUE THREAD

**Issue by Nazeh** [hypercore-protocol/hyperbee#45]
Is it possible to watch the Hypercore `on('append')` event and analyze the latest `seq` to figure out which keys were updated?

If it is not convenient to add this feature in Hyperbee, what can I do to implement that on a higher level of abstraction?

**Comment by Nazeh** [comment]
Ok the solution was in the README.md :)

using `const rs = this.db.createHistoryStream({ reverse: true, limit: 1 })` I managed to figure out what was updated when the `db.feed` emits `append` event

**Comment by mafintosh** [comment]
Protip, use the diff api for that
